name: "imager"
description: "Creates a Raspberry Pi image from a bash script, image.bash"
author: "Jacob Gadikian"
runs:
  using: "composite"
  steps: 
    - run: |
      
      
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
branding:
  icon: "download"
  color: "blue"

