name: "imager"
description: "Creates a Raspberry Pi image from a bash script, image.bash"
author: "Jacob Gadikian"

runs:
  using: composite
  steps:
    - name: Install Environment
      run: ${{ github.action_path }}/installenv.sh
      shell: bash
    - name: Copy ubuntu.json
      run: cp $GITHUB_ACTION_PATH/ubuntu.json .
      shell: bash
    - name: Build Image
      run: packer build ubuntu.json
      shell: bash

branding:
  icon: "download"
  color: "blue"

