name: "imager"
description: "Creates a Raspberry Pi image from a bash script, image.bash"
author: "Jacob Gadikian"
runs:
  using: "composite"
  steps:
    - name: Install Environment
      run: $GITHUB_ACTION_PATH/installenv.sh
      shell: bash
branding:
  icon: "download"
  color: "blue"

