name: "imager"
description: "Creates a Raspberry Pi image from a bash script, image.bash"
author: "Jacob Gadikian"
runs:
  using: "composite"
  steps: 
    - run: |
      DEBIAN_FRONTEND="noninteractive" apt install -y ca-certificates git unzip wget qemu-user-static build-essential qemu-user-static ca-certificates dosfstools gdisk kpartx parted libarchive-tools sudo xz-utils psmisc
      git clone https://github.com/hashicorp/packer --branch v1.5.5
      cd packer
      go mod vendor
      go get .
      go install
      cd ..
      git clone https://github.com//mkaczanowski/packer-builder-arm/
      cd packer-builder-arm
      go mod download
      go install
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
branding:
  icon: "download"
  color: "blue"

